version: "3.8"

services:
  node-app:
    build: .
    container_name: node-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
    command: npm run dev

  caddy:
    image: caddy:2-alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - node-app

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
